### ISSUE TITLE
CI python 3.6 fails -- wxpython fails in ubuntu 20.04

### ISSUE THREAD

**Issue by gfabbris** [APS-4ID-POLAR/polartools#39]
because of `wxpython`

```python
polartools/absorption.py:26: in <module>
22
    from larch.xafs.pre_edge import _finde0
23
/usr/share/miniconda/envs/anaconda-test-env-py-3.6/lib/python3.6/site-packages/larch/__init__.py:50: in <module>
24
    from . import larchlib, utils, version, site_config, apps
25
/usr/share/miniconda/envs/anaconda-test-env-py-3.6/lib/python3.6/site-packages/larch/apps.py:8: in <module>
26
    from .shell import shell
27
/usr/share/miniconda/envs/anaconda-test-env-py-3.6/lib/python3.6/site-packages/larch/shell.py:26: in <module>
28
    import wx
29
/usr/share/miniconda/envs/anaconda-test-env-py-3.6/lib/python3.6/site-packages/wx/__init__.py:12: in <module>
30
    __version__ = wx.__version__.VERSION_STRING
31
E   AttributeError: module 'wx' has no attribute '__version__'
```

**Comment by gfabbris** [comment]
seems like this should not be a problem... https://github.com/xraypy/xraylarch/pull/258

**Comment by gfabbris** [comment]
This error doesn't happen when I test in a fresh environment in my machine....

**Comment by gfabbris** [comment]
The problem is that `wxpython` does not work well with the ubuntu 20.04 that is now the standard for Github Actions. I will temporarily force it to use ubuntu 18.04, but it will be good to sort this.
